### ISSUE TITLE
Passing extra labels while running node cert exporter

### ISSUE THREAD

**Issue by dileepbg** [amimof/node-cert-exporter#30]
- [ ] This feature/enhancement benefits everyone
Yes

**Description**
Thanks for your effort in creating this. I have been actively using this in our company to monitor different certs.

One major difficulty I faced in filtering the certs based on different environment.
We have around 15 environments(Both Production & Internal). It is very difficult to filter the certs based on environments in Grafana. currently we are monitoring 150+ certs across multiple environments.

Is there a way to pass the labels(environment name ) along with path while executing the node-cert-exporter. so that it will be easy in grafana to filter/create a separate table for each environment. It will be good if you can add this has optional parameter.

**Additional information**

**Comment by amimof** [comment]
Hi @dileepbg Thank you for your feedback. I'm pretty sure that you can do this using the labels added by kubernetes-pod job and the autodisovery feature in Prometheus. How do you define an environment? Are they distinguished by namespace?

**Comment by dileepbg** [comment]
@amimof , I could able to filter out using the path specified. Now I could able to segregate the certs in different table in Garfana based on path. 

Need one more support, Currently this exporter supports only .pem/.cert/.cer/.crt . Can you update the exporter to support .pfx format as well. I can create a new issue for this. Closing this thread now.
