### ISSUE TITLE
Exporter broke if can't parse any file

### ISSUE THREAD

**Issue by Asgoret** [amimof/node-cert-exporter#42]
If exporter can't open file it won't expose any data. For example folder with etcd crt file:
```
etcd.conf
ca.crt
```
Exporter error:
`Error looking for certificates in /opt/etc/etcd/: lstat /opt/etc/etcd/etcd.conf: permission denied`

**Comment by amimof** [comment]
Hi, thanks for reporting. Do you mean that if a folder contains the two files `etcd.conf` and `ca.crt`. And if `etcd.conf` causes an error, the exporter wont continue to parse `ca.crt`?

**Comment by Asgoret** [comment]
@amimof Yeah. I think so because I have 3 masters and only on one there is no data about this `ca.crt` but I have error of parsing `etcd.conf`

**Comment by amimof** [comment]
Are you able to replicate this problem elsewhere? Lets say from a docker container on your local host?

**Comment by amimof** [comment]
@Asgoret Please check if latest commit on master branch fixes. #45 might have solved this too.

**Comment by amimof** [comment]
Please reopen if problem persists. Closing meanwhile
