### ISSUE TITLE
Containers are unable to start 

### ISSUE THREAD

**Issue by mack314** [amimof/node-cert-exporter#46]
**Description**
I am deploying this as daemonset in openshift cluster . DS is unable to create containers & failing with below errors in event logs 

 Error: failed to start container "node-cert-exporter": Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "exec: \"--v=2\": executable file not found in $PATH"

**Steps to reproduce the issue:**
1.  used the daemonset file to deploy the  node exporter 
2.
3.

**Describe the results you received:**
 Error: failed to start container "node-cert-exporter": Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "exec: \"--v=2\": executable file not found in $PATH"

**Describe the results you expected:**
no errors and containers should start successfully; 

**Additional information:**

**Output of `node-cert-exporter --version`:**

```
(paste your output here)
```

**Additional environment details:**

**Comment by amimof** [comment]
node-cert-exporter requires `hostPath` privileges and it might be that the Pod is assigned with a SecurityContextContraint that doesn't allow it. Can you verify that this i the case?

**Comment by mack314** [comment]
> node-cert-exporter requires `hostPath` privileges and it might be that the Pod is assigned with a SecurityContextContraint that doesn't allow it. Can you verify that this i the case?

well for the error that caused my issue somehow I was using other cert image . Hence when I use the correct image I was able to resolve the issue.
