### ISSUE TITLE
Need to run the container without root privileges 

### ISSUE THREAD

**Issue by mack314** [amimof/node-cert-exporter#47]
I am running this cert explorer in openshift 3.11 . 

I am able to extract certificate details if I am running this app as root container. But I am unable to extract the certificate details if I am running it as non root e.g with hostaccess SCC. 

Please advise the way to run it as non-root container using sufficient linux capabilities to read certificate files.

**Comment by amimof** [comment]
I don’t believe that it requires root privileges but then again I haven’t tested in OCP myself. Can you provide some logs from inside the container?
