### ISSUE TITLE
Image 1.0.1 does not match release 1.0.1 - ssl_certificate_expiry_failed not implemented

### ISSUE THREAD

**Issue by r2ronoha** [amimof/node-cert-exporter#48]
The docker image tag 1.0.1 does not correspond to changes advertised in release 1.0.1 (i.e. does not implement ssl_certificate_expiry_failed, which I am after).
Would it be possible to have a tag matching the release and the image to be able to pull by release tag, rather than latest?
I would like to be able to pin a specific release to avoid possible outages due to changes to the latest image.

**Comment by amimof** [comment]
@r2ronoha Thanks for reporting. I’ll have a look and will let you know.

**Comment by amimof** [comment]
Just released version [1.0.2](https://github.com/amimof/node-cert-exporter/releases/tag/1.0.2) which includes the new metric
