### ISSUE TITLE
keystore

### ISSUE THREAD

**Issue by rbeherar** [amimof/node-cert-exporter#53]
Hi 

I was trying to monitor the java keystores using the node-cert-keystore but it doesn't do so. It may require password to be passed to view the certificate. 
I saw a package called keystore.go in the pkg.dev.go. Is it possible to integrate this code into your code and compile it to make a new binary?

Kindly can you let us know

**Comment by amimof** [comment]
Hi @rbeherar 👋 
The current implementation only allows for x509 certificates thus not supporting key stores. There is currently no plan to add support for it but you are welcome to contribute. Also, so sorry for the late response!
