### ISSUE TITLE
Old helm release has been overide: 1.0.1

### ISSUE THREAD

**Issue by audig** [amimof/node-cert-exporter#56]
Why has version 1.0.1 been removed, is it voluntary to override the previous release ?
Next release will remove the old one?

We use flux cd helm operator, and it doesn't like when a helm chart disappear from the source repository.

Refer to this commit : https://github.com/amimof/node-cert-exporter/commit/9c516c1ddbea7f9c8a3d2f450f9d08d1855c7c86

**Comment by amimof** [comment]
@audig Thanks for reporting. This is a known issue and I'm trying to figure out a way to solve it.

**Comment by amimof** [comment]
@audig I've migrated away from Travis CI and this project is now using GitHub Actions instead. The Helm chart releaser is much better and new versions are no longer overriding any previous charts. However I had to remove the commit history on the gh-pages branch so the first and only release from a Helm point of view is version 1.1.1.
