### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by kashifest** [amimof/node-cert-exporter#73]
We would need a new release since the last release was almost one and half year ago and new features/fixes have landed after that.

Any plans ?

**Comment by amimof** [comment]
Hi @kashifest thanks for getting in touch. I'm planning on making a new release shortly containing latest PR's and bumped dependencies. Please stick around

**Comment by amimof** [comment]
@kashifest version [1.1.3](https://github.com/amimof/node-cert-exporter/releases/tag/v1.1.3)  was just released
