### ISSUE TITLE
Node Exporter for 32 bits - i686 Linux

### ISSUE THREAD

**Issue by vasile890** [amimof/node-cert-exporter#80]
Hi all,

Thank you for providing this beautiful tool. Is there a way to build the program in order to run on i686 Linux/386 Linux?
I can see it runs on 64 arm and amd.

Super thanks!

**Comment by amimof** [comment]
Hi @vasile890 thanks for the input. I've released a new version with binaries for more platforms. https://github.com/amimof/node-cert-exporter/releases/tag/v1.1.4

I hope this helps! Cheers
