### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by WarpedEdge** [amimof/node-cert-exporter#85]
I saw that the most recent release was in May, however there has been no merging of forked branches and the Go version being used is old. I have tested the 1.19 version of Go and that still worked, and also the https://github.com/amimof/node-cert-exporter/pull/74 has also been tested and works. This would help for people utilizing this exporter that have to remediate any vulnerabilities which these two items have a lot on their older versions.

On the second note, are the containers being stored anywhere besides Dockerhub? That container hasn't been updated for 2 years.

**Comment by amimof** [comment]
Hi @WarpedEdge thank for reaching out. The project is still alive however recently I haven't been able to keep up with maintaining it as much as I want. Feel free to open PR's with improvements and I would be more than happy to look over them. Cheers

**Comment by WarpedEdge** [comment]
People have opened up PRs but you haven't merged any security changes they
have made which is needed to use this as the vulnerabilities itself make
this unusable, which is why I ask if it was alive.

**Comment by amimof** [comment]
I'll make sure to go through them and merge anything that is of value. Thanks for your input
