### ISSUE TITLE
Add ARM container image

### ISSUE THREAD

**Issue by DeltaWhy** [amimof/node-cert-exporter#86]
- [ ] This feature/enhancement benefits everyone

**Description**
Hello, is there any chance we could get a container image for `linux/arm64` added to the registry? I'm interested in using this project on AWS Graviton servers. I'd be happy to work on a PR if this is something you're willing to add.

**Additional information**
The existing Dockerfile works on arm64, so just CI needs to be updated.

**Comment by DeltaWhy** [comment]
Added a PR. If you merge the PR, you will need to tag a new release so that an image gets built with the new workflow.

**Comment by amimof** [comment]
Hi @DeltaWhy Thanks for contributing 👏 Sorry for the late response! This is a great addition addition to the project and I will look over it asap
