### ISSUE TITLE
Only the first entry in exclude-glob is taken into account

### ISSUE THREAD

**Issue by Karandash8** [amimof/node-cert-exporter#89]
**Description**
No matter if you specify multiple exclude-glob entries like
` --exclude-glob "/path/root_ca.pem,/path/*-key.pem"`
or like
`
--exclude-glob "/path/root_ca.pem"
--exclude-glob "/path/*-key.pem"
`
only the first one will be tested against.

**Describe the results you expected:**
All exclude-glob entries shall be tested against.

**Comment by amimof** [comment]
Hi @Karandash8 Thanks for contributing, your patch looks good and should be merged now
